version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - web

  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ''
    command: python /focal-point/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/focal-point
    ports:
      - 8002:8000
    env_file:
      - ./.env.dev
